apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-status
  labels:
    app: finance-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-status
      version: v1
  template:
    metadata:
      labels:
        app: finance-status
        version: v1
    spec:
      containers:
      - name: finance-status
        image: registry.devops.dvpoc.com.br/finance-status
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: cm-kafka-op
        - secretRef:
            name: sc-azure-data
---
apiVersion: v1
kind: Service
metadata:
  name: finance-status
spec:
  selector:
    app: finance-status
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: finance-status
spec:
  gateways:
    - default/default
  hosts:
  - finance-status.istio.dvpoc.com.br
  http:
  - name: "http-routes"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: finance-status
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: finance-status
spec:
  host: finance-status
  subsets:
  - name: v1
    labels:
      version: v1
